#!/usr/bin/awk -f
BEGIN {
	FS = "\t"
	subtipo = 1
	componente = 2
	comunidad = 3
	kegg = 4
	gobp = 5
	gdcc = 6
	gomf = 7
	nrow = 1 # contador de fila
	ncol = 1 # contador de columna
	OFS = "\t"
	ORS = "\n"
	colnames[1] = "SUBTYPE"
}
NR > 1 {
	# Generar los índices para mostrar la info

	# seleccionar la columna de interés
	search = kegg
	split($search, array, ";")

	rownames[nrow] = $subtipo "_" $componente "_" $comunidad

	for (i = 1; i <= length(array); i++) {
		id = array[i]

		# descartar elemento vacío
		if (id == "X") { continue }

		# limpiar id para evitar repetidos
		gsub(/^[ \t]+|[ \t]+$/, "", id)

		if (!(columns[id])) {
			columns[id] = ncol
			colnames[ncol] = id
			ncol += 1
		}
		rows[nrow][columns[id]] = 1
	}

	nrow += 1
}
END {
	# HEADER
	printf(OFS) # name
	# print colnames
	for (col = 1; col < ncol; col++) {
		printf(colnames[col] OFS)
	}
	printf(ORS)

	# matrix
	for (row = 1; row < nrow; row++) {
		printf(rownames[row] OFS) #name
		for (col = 1; col < ncol; col++) {
			printf((rows[row][col] == 1 ? 1 : 0) OFS)
		}
		printf(ORS)
		row += 1
	}

}
