#!/usr/bin/awk -f
BEGIN {
	FS=","
	subtipo=1
	componente=2
	comunidad=3
	kegg=4
	gobp=5
	gdcc=6
	gomf=7
	n=1 #Contador para ID de columna
	OFS=","
	ORS="\n"
	colnames[1]="SUBTYPE"
}
NR > 1 {
	# Generar los índices para mostrar la info
	split($kegg, array, ";")
	for (i=1; i <= length(array); i++) {
		gsub(/^[ \t]+|[ \t]+$|^X$/, "", array[i])
		if (!(columns[array[i]])) {
			columns[array[i]] = n
			colnames[i] = array[i]
			n+=1
		}
		names[NR] = $subtipo
		rows[NR][columns[array[i]]] = 1
	}
}
END {
	# HEADER
	printf(OFS) # name
	col=1
	for (var in columns) {
		printf(colnames[col] OFS)
		col+=1
	}
	printf(ORS)

	# matrix
	row = 1
	for (var in rows) {
		printf(names[row] OFS) #name
		for (col=1; col<=n; col++) {
			printf((rows[row][col] == 1 ? 1 : 0) OFS)
		}
		printf(ORS)
		row += 1
	}
	
}
